baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Dan La Scala'
theme  = 'hugo-coder'



[params]
  author = "Dan La Scala"
  info = "System Administration and Technical Operations Specialist"
  avatarurl = "images/prof.png"
  colorScheme = "dark"

[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/dls-repo"

[[params.social]]
  name = "LinkedIn"
  icon = "fa-brands fa-linkedin fa-2x"
  weight = 1
  url = "https://www.linkedin.com/in/daniel-la-scala-7094031ab/"

# Menu links
[[menu.main]]
  name = "About Me"
  weight = 1
  url  = "about/"
[[menu.main]]
  name = "Contact Me"
  weight = 2
  url = "contact/"
